import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown } from 'lucide-react';
import { sounds } from '../../utils/sound';

interface ScreenProps {
  onNext: () => void;
}

interface FaqItem {
  id: number;
  question: string;
  category?: string;
  answer: string;
}

const FAQS: FaqItem[] = [
  {
    id: 1,
    category: 'Profile & Privacy',
    question: 'How much of the information I shared during the voice conversation will be used publicly?',
    answer:
      'Only the content you explicitly approve during the profile editing process will ever be shared on Rivet. Your raw audio conversations are strictly confidential and never published without your direct consent.',
  },
  {
    id: 2,
    question: 'How are Rivet profiles created?',
    answer:
      'Profiles are built through a guided natural voice interview that captures your personality, values, and humor without you having to fill out tedious forms.',
  },
  {
    id: 3,
    question: 'Can I choose which profile details are highlighted?',
    answer:
      'Yes, absolutely. You retain 100% editorial control over which voice snippets, photos, and match preferences appear on your public card.',
  },
  {
    id: 4,
    question: 'I do not like the image and/or content generated by Rivet...',
    answer:
      'You can re-record, regenerate, or replace any element with one tap at any point before or after publishing.',
  },
];

export const FaqScreen: React.FC<ScreenProps> = () => {
  const [openId, setOpenId] = useState<number | null>(1); // 1 is expanded initially matching video

  const toggle = (id: number, e: React.MouseEvent) => {
    e.stopPropagation();
    sounds.playTap();
    setOpenId((prev) => (prev === id ? null : id));
  };

  return (
    <div
      data-no-advance="true"
      className="relative w-full max-w-2xl mx-auto flex flex-col justify-between px-6 py-4 sm:py-8 select-none"
    >
      {/* Top Header */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="text-left mb-3 pt-1"
      >
        <span className="text-[10px] font-bold uppercase tracking-wider text-[#FF2E93] bg-pink-50 px-2.5 py-0.5 rounded-full border border-pink-100">
          FAQ
        </span>
        <h2 className="text-2xl sm:text-3xl font-black text-gray-900 tracking-tight leading-tight mt-1.5">
          Got a question? <span className="text-[#FF2E93]">Most do!</span>
        </h2>
      </motion.div>

      {/* Accordion list */}
      <div className="relative z-20 space-y-2.5 overflow-y-auto no-scrollbar max-h-[460px] pr-0.5 my-auto">
        {FAQS.map((item) => {
          const isOpen = openId === item.id;

          return (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: item.id * 0.08 }}
              className={`rounded-2xl border transition-all ${
                isOpen
                  ? 'bg-white border-pink-200 shadow-md ring-1 ring-pink-100'
                  : 'bg-white/80 border-gray-200/60 hover:bg-white hover:border-gray-300'
              }`}
            >
              <button
                onClick={(e) => toggle(item.id, e)}
                className="w-full p-3.5 text-left flex items-start justify-between gap-2.5 focus:outline-none"
              >
                <div className="flex-1">
                  {item.category && (
                    <span className="text-[10px] uppercase font-bold text-[#FF2E93] tracking-wider block mb-0.5">
                      {item.category}
                    </span>
                  )}
                  <h4 className="text-xs sm:text-sm font-bold text-gray-900 leading-snug">
                    {item.question}
                  </h4>
                </div>
                <motion.div
                  animate={{ rotate: isOpen ? 180 : 0 }}
                  transition={{ duration: 0.25 }}
                  className="flex-shrink-0 text-gray-400 mt-0.5"
                >
                  <ChevronDown className="w-4 h-4 text-gray-600" />
                </motion.div>
              </button>

              <AnimatePresence initial={false}>
                {isOpen && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.25, ease: 'easeInOut' }}
                    className="overflow-hidden"
                  >
                    <div className="px-3.5 pb-3.5 text-[11px] sm:text-xs font-normal text-gray-600 leading-relaxed border-t border-gray-100 pt-2.5">
                      {item.answer}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          );
        })}
      </div>

      <div className="text-center text-[10px] text-gray-400 mt-2">
        Click any question to view answers
      </div>
    </div>
  );
};
